Address the no liquidity in pool error
This is occurring right now when force withdrawing the wstETH_USD market on Neutron mainnet. Not sure this is the right solution or not.

2026-06-18T01:06:45.546822Z  INFO perps_deploy::mainnet::force_withdraw_all: Force withdrawing all funds in wstETH_USD
Error: ForceWithdrawAll simulation failed for wstETH_USD

Caused by:
    0: On connection to https://grpc-lb.neutron.org/, while performing:
       simulating transaction: Message 0: neutron1e2r98hpf3eer8pfpcrsprmrx5vpfq8jpc2r4tg executing contract neutron1lkm345465c0gy0m0tehq8h0kkkfdcttr039wejs053mdv27pzndqw3hnv7 with message: {"force_withdraw_all":{"limit":null}}
       Failed to execute message: status: Unknown, message: "failed to execute message; message index: 0: LiquidityStats::lp_to_collateral: no liquidity is in the pool: execute wasm contract failed [CosmWasm/wasmd@v0.61.0/x/wasm/keeper/keeper.go:457] with gas used: '244932'", details: [], metadata: MetadataMap { headers: {"date": "Thu, 18 Jun 2026 01:06:45 GMT", "content-type": "application/grpc", "via": "2.0 Caddy", "x-cosmos-block-height": "59391332", "cf-cache-status": "DYNAMIC", "server": "cloudflare", "cf-ray": "a0d664abacafb546-LHR", "alt-svc": "h3=\":443\"; ma=86400"} }