MPA: Fix issue with ETH_USD market
This fixes the crash issue:

Error: error decoding response body: invalid value: string "ETH_DAI+", expected Valid market id at line 1 column 1351724

Caused by:
    invalid value: string "ETH_DAI+", expected Valid market id at line 1 column 1351724

There is no reason to denote the data we get from CMC api as MarketId
type since that's not used anywhere.